crawlings/urls.py
from django.urls import path
from . import views

app_name = 'crawlings'
urlpatterns = [
    path('index/', views.index, name='index'),    # 사용자 입력받아서 종목 토론 데이터 검색하기 -> 검색한 결과(토론 목록)을 출력
    path('delete_comment/', views.delete_comment, name='delete_comment'),    # 댓글 목록에서 하나 삭제

]

stock_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('crawlings/', include('crawlings.urls')),
]

crawlings/models.py
from django.db import models

# 주식 모델
class Stock(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=6)
    updated_at = models.DateField(auto_now=True)


# 댓글 모델
class Comment(models.Model):
    # Stock 모델 가져옴.
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)

summaries/models.py
from django.db import models
from crawlings.models import Comment

# Create your models here.
class Summary(models.Model):
    summary = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    related_comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    # 혹은 종목이나 다른 엔티티와 직접 연결

crawlings/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    stock_name = forms.CharField(max_length=100)

    class Meta:
        model = Comment
        fields = ('stock_name', )    # 사용자로부터 입력받을 필드

crawlings/views.py
from django.shortcuts import render, get_object_or_404

from .models import Stock, Comment
# from .forms import CommentForm
from .utils import get_toss_data

# 사용자 입력을 받을 수 있도록 stock_finder.html 렌더링
def index(request):
    # 폼을 띄워서 검색할 수 있도록 한다.
    if request.method == 'POST':
        
        keyword = request.POST.get('stock_name')

        # 크롤링하기
        stock_name, stock_code, contents = get_toss_data(keyword)

        # DB에 있는지 확인하는 작업 필요!
        stock, created = Stock.objects.get_or_create(
            code=stock_code,
            defaults={'name': stock_name}    # 새롭게 생성할 때만 적용
        )

        if not created and stock.name != stock_name:    # 기존에 있던 내용이라면
            stock.name = stock_name
            stock.save()    # 저장

        # 댓글도 저장하기
        for content in contents:
            comment = Comment(stock=stock, content=content)
            comment.save()

        # 검색한 결과의 댓글 목록을 출력한다.
        comments = stock.comments.all()

        context = {
            'stock': stock,
            'comments': comments,
        }
        
        return render(request, 'crawlings/stock_finder.html', context)
 
    return render(request, 'crawlings/stock_finder.html')
    
    
# 특정 토론 데이터 삭제
def delete_comment(request):
    if request.method == 'POST':
        # 숨김 처리해서 가져온 데이터 받기기
        comment_pk = request.POST.get('comment_pk')
        stock_code = request.POST.get('stock_code')
        
        comment = get_object_or_404(Comment, pk=comment_pk)
        comment.delete()

        stock = get_object_or_404(Stock, code=stock_code)
        comments = stock.comments.all()

        context = {
            'stock' : stock,
            'comments': comments,
        }

        return render(request, 'crawlings/stock_finder.html', context)

summaries/views.py
from django.shortcuts import render

# Create your views here.

crawlings/templates/crawlings/stock_finder.html
{% extends "base.html" %}

{% comment %} 사용자 입력받을 수 있도록 하는 페이지 {% endcomment %}

{% block content %}
    
    <div class='title'>
        <p>주식에 대한, 투자자들의 목소리</p>
        <h1>주식 댓글 분석기</h1>
    </div>
    
    <form action="{% url "crawlings:index" %}" method='POST'>
        {% csrf_token %}

        <label for="stock_name">회사 이름을 입력하세요 : </label>
        <input type="text" name='stock_name'>
        {% if stock %}
            <input type="hidden" name='stock_code' value='{{ stock.code }}'>
        {% endif %}
        <input type="submit" value='검색'>
        
    </form>

    {% if stock %}
        <h2>{{ stock.name }} ({{ stock.code }})</h2>
        <h3>수집된 댓글:</h3>
        <ul>
            {% for comment in comments %}
                <li>
                    {{ comment.content }}
                    <form action="{% url "crawlings:delete_comment" %}" method='POST'>
                        {% csrf_token %}
                        <input type="hidden" name='comment_pk' value='{{ comment.pk }}'>
                        <input type="hidden" name='stock_code', value='{{ stock.code }}'>
                        <button type='submit'>삭제</button>
                    </form>
                </li>
            {% endfor %}
        </ul>

    {% endif %}

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .title {
            margin-left: 20px;
        }
    </style>
</head>
<body>
    {% block content %}
    {% endblock content %}
</body>
</html>